{{- if .Values.serviceAccount.create -}}
{{- if .Values.serviceAccount.clusterAdmin -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "etalab-website.fullname" . }}
  labels:
    {{- include "etalab-website.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "etalab-website.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}